// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Suchimu.Server.Data;

namespace Suchimu.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220514161139_Stats")]
    partial class Stats
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Suchimu.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "FPS",
                            Url = "game-category-FPS"
                        },
                        new
                        {
                            Id = 2,
                            Name = "RPG",
                            Url = "game-category-RPG"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sports",
                            Url = "game-category-sports"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Indie",
                            Url = "game-category-indie"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Platformer",
                            Url = "game-category-platformer"
                        },
                        new
                        {
                            Id = 6,
                            Name = "3D",
                            Url = "game-category-3d"
                        });
                });

            modelBuilder.Entity("Suchimu.Shared.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LatestUpdate")
                        .HasColumnType("datetime2");

                    b.Property<double>("OriginalPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudioId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StudioId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            CreateDate = new DateTime(2022, 5, 14, 23, 11, 38, 855, DateTimeKind.Local).AddTicks(7415),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec orci nibh, fermentum eget ligula nec, dapibus aliquet nibh. In hac habitasse platea dictumst. Proin consectetur ornare tristique. Integer nec pulvinar ipsum. Mauris venenatis mi varius, accumsan metus ut, porttitor dolor. Sed risus nisl, lacinia venenatis dapibus interdum, facilisis vel erat. Suspendisse vitae pulvinar nisi. Quisque pretium venenatis ante in hendrerit. Donec rhoncus pulvinar scelerisque. Curabitur condimentum ut lacus sed aliquet. Mauris blandit, dolor non interdum bibendum, nunc neque porta mauris, sed egestas diam nibh non sapien. Aliquam vel bibendum nibh, eu luctus tellus. Nam urna tortor, tristique in velit ut, tempus consequat leo. Praesent elementum congue dui, non sagittis ipsum fermentum eu.",
                            ImageUrl = "https://i.scdn.co/image/ab67616d0000b273c634cd65ba525a56904e94bd",
                            IsActive = true,
                            LatestUpdate = new DateTime(2022, 5, 14, 23, 11, 38, 856, DateTimeKind.Local).AddTicks(9834),
                            OriginalPrice = 100000.0,
                            Price = 100000.0,
                            ShortDescription = "Deez Nut haha, Gothem",
                            StudioId = 6,
                            Title = "Fifa 10"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            CreateDate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5039),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec orci nibh, fermentum eget ligula nec, dapibus aliquet nibh. In hac habitasse platea dictumst. Proin consectetur ornare tristique. Integer nec pulvinar ipsum. Mauris venenatis mi varius, accumsan metus ut, porttitor dolor. Sed risus nisl, lacinia venenatis dapibus interdum, facilisis vel erat. Suspendisse vitae pulvinar nisi. Quisque pretium venenatis ante in hendrerit. Donec rhoncus pulvinar scelerisque. Curabitur condimentum ut lacus sed aliquet. Mauris blandit, dolor non interdum bibendum, nunc neque porta mauris, sed egestas diam nibh non sapien. Aliquam vel bibendum nibh, eu luctus tellus. Nam urna tortor, tristique in velit ut, tempus consequat leo. Praesent elementum congue dui, non sagittis ipsum fermentum eu.",
                            ImageUrl = "https://i.scdn.co/image/ab67616d0000b273c634cd65ba525a56904e94bd",
                            IsActive = true,
                            LatestUpdate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5049),
                            OriginalPrice = 100000.0,
                            Price = 100000.0,
                            ShortDescription = "Deez Nut haha, Gothem",
                            StudioId = 6,
                            Title = "Fifa 11"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreateDate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5056),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec orci nibh, fermentum eget ligula nec, dapibus aliquet nibh. In hac habitasse platea dictumst. Proin consectetur ornare tristique. Integer nec pulvinar ipsum. Mauris venenatis mi varius, accumsan metus ut, porttitor dolor. Sed risus nisl, lacinia venenatis dapibus interdum, facilisis vel erat. Suspendisse vitae pulvinar nisi. Quisque pretium venenatis ante in hendrerit. Donec rhoncus pulvinar scelerisque. Curabitur condimentum ut lacus sed aliquet. Mauris blandit, dolor non interdum bibendum, nunc neque porta mauris, sed egestas diam nibh non sapien. Aliquam vel bibendum nibh, eu luctus tellus. Nam urna tortor, tristique in velit ut, tempus consequat leo. Praesent elementum congue dui, non sagittis ipsum fermentum eu.",
                            ImageUrl = "https://i.scdn.co/image/ab67616d0000b273c634cd65ba525a56904e94bd",
                            IsActive = true,
                            LatestUpdate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5057),
                            OriginalPrice = 100000.0,
                            Price = 100000.0,
                            ShortDescription = "Deez Nut haha, Gothem",
                            StudioId = 6,
                            Title = "Fifa 12"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            CreateDate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5061),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec orci nibh, fermentum eget ligula nec, dapibus aliquet nibh. In hac habitasse platea dictumst. Proin consectetur ornare tristique. Integer nec pulvinar ipsum. Mauris venenatis mi varius, accumsan metus ut, porttitor dolor. Sed risus nisl, lacinia venenatis dapibus interdum, facilisis vel erat. Suspendisse vitae pulvinar nisi. Quisque pretium venenatis ante in hendrerit. Donec rhoncus pulvinar scelerisque. Curabitur condimentum ut lacus sed aliquet. Mauris blandit, dolor non interdum bibendum, nunc neque porta mauris, sed egestas diam nibh non sapien. Aliquam vel bibendum nibh, eu luctus tellus. Nam urna tortor, tristique in velit ut, tempus consequat leo. Praesent elementum congue dui, non sagittis ipsum fermentum eu.",
                            ImageUrl = "https://i.scdn.co/image/ab67616d0000b273c634cd65ba525a56904e94bd",
                            IsActive = true,
                            LatestUpdate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5062),
                            OriginalPrice = 100000.0,
                            Price = 100000.0,
                            ShortDescription = "Deez Nut haha, Gothem",
                            StudioId = 6,
                            Title = "Fifa 13"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CreateDate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5065),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec orci nibh, fermentum eget ligula nec, dapibus aliquet nibh. In hac habitasse platea dictumst. Proin consectetur ornare tristique. Integer nec pulvinar ipsum. Mauris venenatis mi varius, accumsan metus ut, porttitor dolor. Sed risus nisl, lacinia venenatis dapibus interdum, facilisis vel erat. Suspendisse vitae pulvinar nisi. Quisque pretium venenatis ante in hendrerit. Donec rhoncus pulvinar scelerisque. Curabitur condimentum ut lacus sed aliquet. Mauris blandit, dolor non interdum bibendum, nunc neque porta mauris, sed egestas diam nibh non sapien. Aliquam vel bibendum nibh, eu luctus tellus. Nam urna tortor, tristique in velit ut, tempus consequat leo. Praesent elementum congue dui, non sagittis ipsum fermentum eu.",
                            ImageUrl = "https://i.scdn.co/image/ab67616d0000b273c634cd65ba525a56904e94bd",
                            IsActive = true,
                            LatestUpdate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5067),
                            OriginalPrice = 100000.0,
                            Price = 100000.0,
                            ShortDescription = "Deez Nut haha, Gothem",
                            StudioId = 6,
                            Title = "Fifa 14"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreateDate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5073),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec orci nibh, fermentum eget ligula nec, dapibus aliquet nibh. In hac habitasse platea dictumst. Proin consectetur ornare tristique. Integer nec pulvinar ipsum. Mauris venenatis mi varius, accumsan metus ut, porttitor dolor. Sed risus nisl, lacinia venenatis dapibus interdum, facilisis vel erat. Suspendisse vitae pulvinar nisi. Quisque pretium venenatis ante in hendrerit. Donec rhoncus pulvinar scelerisque. Curabitur condimentum ut lacus sed aliquet. Mauris blandit, dolor non interdum bibendum, nunc neque porta mauris, sed egestas diam nibh non sapien. Aliquam vel bibendum nibh, eu luctus tellus. Nam urna tortor, tristique in velit ut, tempus consequat leo. Praesent elementum congue dui, non sagittis ipsum fermentum eu.",
                            ImageUrl = "https://i.scdn.co/image/ab67616d0000b273c634cd65ba525a56904e94bd",
                            IsActive = true,
                            LatestUpdate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5074),
                            OriginalPrice = 100000.0,
                            Price = 100000.0,
                            ShortDescription = "Deez Nut haha, Gothem",
                            StudioId = 6,
                            Title = "Fifa 15"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreateDate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5077),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec orci nibh, fermentum eget ligula nec, dapibus aliquet nibh. In hac habitasse platea dictumst. Proin consectetur ornare tristique. Integer nec pulvinar ipsum. Mauris venenatis mi varius, accumsan metus ut, porttitor dolor. Sed risus nisl, lacinia venenatis dapibus interdum, facilisis vel erat. Suspendisse vitae pulvinar nisi. Quisque pretium venenatis ante in hendrerit. Donec rhoncus pulvinar scelerisque. Curabitur condimentum ut lacus sed aliquet. Mauris blandit, dolor non interdum bibendum, nunc neque porta mauris, sed egestas diam nibh non sapien. Aliquam vel bibendum nibh, eu luctus tellus. Nam urna tortor, tristique in velit ut, tempus consequat leo. Praesent elementum congue dui, non sagittis ipsum fermentum eu.",
                            ImageUrl = "https://i.scdn.co/image/ab67616d0000b273c634cd65ba525a56904e94bd",
                            IsActive = true,
                            LatestUpdate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5078),
                            OriginalPrice = 100000.0,
                            Price = 100000.0,
                            ShortDescription = "Deez Nut haha, Gothem",
                            StudioId = 6,
                            Title = "Fifa 16"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreateDate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5081),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec orci nibh, fermentum eget ligula nec, dapibus aliquet nibh. In hac habitasse platea dictumst. Proin consectetur ornare tristique. Integer nec pulvinar ipsum. Mauris venenatis mi varius, accumsan metus ut, porttitor dolor. Sed risus nisl, lacinia venenatis dapibus interdum, facilisis vel erat. Suspendisse vitae pulvinar nisi. Quisque pretium venenatis ante in hendrerit. Donec rhoncus pulvinar scelerisque. Curabitur condimentum ut lacus sed aliquet. Mauris blandit, dolor non interdum bibendum, nunc neque porta mauris, sed egestas diam nibh non sapien. Aliquam vel bibendum nibh, eu luctus tellus. Nam urna tortor, tristique in velit ut, tempus consequat leo. Praesent elementum congue dui, non sagittis ipsum fermentum eu.",
                            ImageUrl = "https://i.scdn.co/image/ab67616d0000b273c634cd65ba525a56904e94bd",
                            IsActive = true,
                            LatestUpdate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5082),
                            OriginalPrice = 100000.0,
                            Price = 100000.0,
                            ShortDescription = "Deez Nut haha, Gothem",
                            StudioId = 6,
                            Title = "Fifa 17"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreateDate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5085),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec orci nibh, fermentum eget ligula nec, dapibus aliquet nibh. In hac habitasse platea dictumst. Proin consectetur ornare tristique. Integer nec pulvinar ipsum. Mauris venenatis mi varius, accumsan metus ut, porttitor dolor. Sed risus nisl, lacinia venenatis dapibus interdum, facilisis vel erat. Suspendisse vitae pulvinar nisi. Quisque pretium venenatis ante in hendrerit. Donec rhoncus pulvinar scelerisque. Curabitur condimentum ut lacus sed aliquet. Mauris blandit, dolor non interdum bibendum, nunc neque porta mauris, sed egestas diam nibh non sapien. Aliquam vel bibendum nibh, eu luctus tellus. Nam urna tortor, tristique in velit ut, tempus consequat leo. Praesent elementum congue dui, non sagittis ipsum fermentum eu.",
                            ImageUrl = "https://i.scdn.co/image/ab67616d0000b273c634cd65ba525a56904e94bd",
                            IsActive = true,
                            LatestUpdate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5086),
                            OriginalPrice = 300000.0,
                            Price = 150000.0,
                            ShortDescription = "Deez Nut haha, Gothem",
                            StudioId = 6,
                            Title = "Fifa 18"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            CreateDate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5090),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec orci nibh, fermentum eget ligula nec, dapibus aliquet nibh. In hac habitasse platea dictumst. Proin consectetur ornare tristique. Integer nec pulvinar ipsum. Mauris venenatis mi varius, accumsan metus ut, porttitor dolor. Sed risus nisl, lacinia venenatis dapibus interdum, facilisis vel erat. Suspendisse vitae pulvinar nisi. Quisque pretium venenatis ante in hendrerit. Donec rhoncus pulvinar scelerisque. Curabitur condimentum ut lacus sed aliquet. Mauris blandit, dolor non interdum bibendum, nunc neque porta mauris, sed egestas diam nibh non sapien. Aliquam vel bibendum nibh, eu luctus tellus. Nam urna tortor, tristique in velit ut, tempus consequat leo. Praesent elementum congue dui, non sagittis ipsum fermentum eu.",
                            ImageUrl = "https://i.scdn.co/image/ab67616d0000b273c634cd65ba525a56904e94bd",
                            IsActive = true,
                            LatestUpdate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5092),
                            OriginalPrice = 400000.0,
                            Price = 300000.0,
                            ShortDescription = "Deez Nut haha, Gothem",
                            StudioId = 6,
                            Title = "Fifa 19"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CreateDate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5094),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec orci nibh, fermentum eget ligula nec, dapibus aliquet nibh. In hac habitasse platea dictumst. Proin consectetur ornare tristique. Integer nec pulvinar ipsum. Mauris venenatis mi varius, accumsan metus ut, porttitor dolor. Sed risus nisl, lacinia venenatis dapibus interdum, facilisis vel erat. Suspendisse vitae pulvinar nisi. Quisque pretium venenatis ante in hendrerit. Donec rhoncus pulvinar scelerisque. Curabitur condimentum ut lacus sed aliquet. Mauris blandit, dolor non interdum bibendum, nunc neque porta mauris, sed egestas diam nibh non sapien. Aliquam vel bibendum nibh, eu luctus tellus. Nam urna tortor, tristique in velit ut, tempus consequat leo. Praesent elementum congue dui, non sagittis ipsum fermentum eu.",
                            ImageUrl = "https://i.scdn.co/image/ab67616d0000b273c634cd65ba525a56904e94bd",
                            IsActive = true,
                            LatestUpdate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5096),
                            OriginalPrice = 750000.0,
                            Price = 500000.0,
                            ShortDescription = "Deez Nut haha, Gothem",
                            StudioId = 6,
                            Title = "Fifa 20"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            CreateDate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5099),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec orci nibh, fermentum eget ligula nec, dapibus aliquet nibh. In hac habitasse platea dictumst. Proin consectetur ornare tristique. Integer nec pulvinar ipsum. Mauris venenatis mi varius, accumsan metus ut, porttitor dolor. Sed risus nisl, lacinia venenatis dapibus interdum, facilisis vel erat. Suspendisse vitae pulvinar nisi. Quisque pretium venenatis ante in hendrerit. Donec rhoncus pulvinar scelerisque. Curabitur condimentum ut lacus sed aliquet. Mauris blandit, dolor non interdum bibendum, nunc neque porta mauris, sed egestas diam nibh non sapien. Aliquam vel bibendum nibh, eu luctus tellus. Nam urna tortor, tristique in velit ut, tempus consequat leo. Praesent elementum congue dui, non sagittis ipsum fermentum eu.",
                            ImageUrl = "https://i.scdn.co/image/ab67616d0000b273c634cd65ba525a56904e94bd",
                            IsActive = true,
                            LatestUpdate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5100),
                            OriginalPrice = 70000.0,
                            Price = 70000.0,
                            ShortDescription = "Deez Nut haha, Gothem",
                            StudioId = 5,
                            Title = "Doom 1"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            CreateDate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5103),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec orci nibh, fermentum eget ligula nec, dapibus aliquet nibh. In hac habitasse platea dictumst. Proin consectetur ornare tristique. Integer nec pulvinar ipsum. Mauris venenatis mi varius, accumsan metus ut, porttitor dolor. Sed risus nisl, lacinia venenatis dapibus interdum, facilisis vel erat. Suspendisse vitae pulvinar nisi. Quisque pretium venenatis ante in hendrerit. Donec rhoncus pulvinar scelerisque. Curabitur condimentum ut lacus sed aliquet. Mauris blandit, dolor non interdum bibendum, nunc neque porta mauris, sed egestas diam nibh non sapien. Aliquam vel bibendum nibh, eu luctus tellus. Nam urna tortor, tristique in velit ut, tempus consequat leo. Praesent elementum congue dui, non sagittis ipsum fermentum eu.",
                            ImageUrl = "https://i.scdn.co/image/ab67616d0000b273c634cd65ba525a56904e94bd",
                            IsActive = true,
                            LatestUpdate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5104),
                            OriginalPrice = 120000.0,
                            Price = 100000.0,
                            ShortDescription = "Deez Nut haha, Gothem",
                            StudioId = 5,
                            Title = "Doom 2"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            CreateDate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5107),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec orci nibh, fermentum eget ligula nec, dapibus aliquet nibh. In hac habitasse platea dictumst. Proin consectetur ornare tristique. Integer nec pulvinar ipsum. Mauris venenatis mi varius, accumsan metus ut, porttitor dolor. Sed risus nisl, lacinia venenatis dapibus interdum, facilisis vel erat. Suspendisse vitae pulvinar nisi. Quisque pretium venenatis ante in hendrerit. Donec rhoncus pulvinar scelerisque. Curabitur condimentum ut lacus sed aliquet. Mauris blandit, dolor non interdum bibendum, nunc neque porta mauris, sed egestas diam nibh non sapien. Aliquam vel bibendum nibh, eu luctus tellus. Nam urna tortor, tristique in velit ut, tempus consequat leo. Praesent elementum congue dui, non sagittis ipsum fermentum eu.",
                            ImageUrl = "https://i.scdn.co/image/ab67616d0000b273c634cd65ba525a56904e94bd",
                            IsActive = true,
                            LatestUpdate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5108),
                            OriginalPrice = 750000.0,
                            Price = 500000.0,
                            ShortDescription = "Deez Nut haha, Gothem",
                            StudioId = 5,
                            Title = "Doom 2016"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            CreateDate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5111),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec orci nibh, fermentum eget ligula nec, dapibus aliquet nibh. In hac habitasse platea dictumst. Proin consectetur ornare tristique. Integer nec pulvinar ipsum. Mauris venenatis mi varius, accumsan metus ut, porttitor dolor. Sed risus nisl, lacinia venenatis dapibus interdum, facilisis vel erat. Suspendisse vitae pulvinar nisi. Quisque pretium venenatis ante in hendrerit. Donec rhoncus pulvinar scelerisque. Curabitur condimentum ut lacus sed aliquet. Mauris blandit, dolor non interdum bibendum, nunc neque porta mauris, sed egestas diam nibh non sapien. Aliquam vel bibendum nibh, eu luctus tellus. Nam urna tortor, tristique in velit ut, tempus consequat leo. Praesent elementum congue dui, non sagittis ipsum fermentum eu.",
                            ImageUrl = "https://i.scdn.co/image/ab67616d0000b273c634cd65ba525a56904e94bd",
                            IsActive = true,
                            LatestUpdate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5112),
                            OriginalPrice = 1050000.0,
                            Price = 750000.0,
                            ShortDescription = "Deez Nut haha, Gothem",
                            StudioId = 5,
                            Title = "Doom Eternal"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            CreateDate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5116),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec orci nibh, fermentum eget ligula nec, dapibus aliquet nibh. In hac habitasse platea dictumst. Proin consectetur ornare tristique. Integer nec pulvinar ipsum. Mauris venenatis mi varius, accumsan metus ut, porttitor dolor. Sed risus nisl, lacinia venenatis dapibus interdum, facilisis vel erat. Suspendisse vitae pulvinar nisi. Quisque pretium venenatis ante in hendrerit. Donec rhoncus pulvinar scelerisque. Curabitur condimentum ut lacus sed aliquet. Mauris blandit, dolor non interdum bibendum, nunc neque porta mauris, sed egestas diam nibh non sapien. Aliquam vel bibendum nibh, eu luctus tellus. Nam urna tortor, tristique in velit ut, tempus consequat leo. Praesent elementum congue dui, non sagittis ipsum fermentum eu.",
                            ImageUrl = "https://i.scdn.co/image/ab67616d0000b273c634cd65ba525a56904e94bd",
                            IsActive = true,
                            LatestUpdate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5117),
                            OriginalPrice = 1050000.0,
                            Price = 750000.0,
                            ShortDescription = "Deez Nut haha, Gothem",
                            StudioId = 7,
                            Title = "Half life 1"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            CreateDate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5199),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec orci nibh, fermentum eget ligula nec, dapibus aliquet nibh. In hac habitasse platea dictumst. Proin consectetur ornare tristique. Integer nec pulvinar ipsum. Mauris venenatis mi varius, accumsan metus ut, porttitor dolor. Sed risus nisl, lacinia venenatis dapibus interdum, facilisis vel erat. Suspendisse vitae pulvinar nisi. Quisque pretium venenatis ante in hendrerit. Donec rhoncus pulvinar scelerisque. Curabitur condimentum ut lacus sed aliquet. Mauris blandit, dolor non interdum bibendum, nunc neque porta mauris, sed egestas diam nibh non sapien. Aliquam vel bibendum nibh, eu luctus tellus. Nam urna tortor, tristique in velit ut, tempus consequat leo. Praesent elementum congue dui, non sagittis ipsum fermentum eu.",
                            ImageUrl = "https://i.scdn.co/image/ab67616d0000b273c634cd65ba525a56904e94bd",
                            IsActive = true,
                            LatestUpdate = new DateTime(2022, 5, 14, 23, 11, 38, 857, DateTimeKind.Local).AddTicks(5201),
                            OriginalPrice = 1050000.0,
                            Price = 750000.0,
                            ShortDescription = "Deez Nut haha, Gothem",
                            StudioId = 7,
                            Title = "Half life 2"
                        });
                });

            modelBuilder.Entity("Suchimu.Shared.Stats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("LastVisit")
                        .HasColumnType("datetime2");

                    b.Property<int>("Visits")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("Suchimu.Shared.Studio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Studios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "contact@konami.com",
                            ImageUrl = "https://slotcatalog.com/userfiles/image/brand/Konami_m.jpg",
                            Location = "Japan",
                            Name = "Konami",
                            Url = "studio_konami"
                        },
                        new
                        {
                            Id = 2,
                            Email = "contact@nintendo.com",
                            ImageUrl = "https://slotcatalog.com/userfiles/image/brand/Konami_m.jpg",
                            Location = "Japan",
                            Name = "Nintendo",
                            Url = "studio_nintendo"
                        },
                        new
                        {
                            Id = 3,
                            Email = "contact@sega.com",
                            ImageUrl = "https://slotcatalog.com/userfiles/image/brand/Konami_m.jpg",
                            Location = "Japan",
                            Name = "SEGA",
                            Url = "studio_sega"
                        },
                        new
                        {
                            Id = 4,
                            Email = "contact@bankai_namco.com",
                            ImageUrl = "https://slotcatalog.com/userfiles/image/brand/Konami_m.jpg",
                            Location = "Japan",
                            Name = "Bankai Namco",
                            Url = "studio_bankai_namco"
                        },
                        new
                        {
                            Id = 5,
                            Email = "contact@bathesda.com",
                            ImageUrl = "https://i0.wp.com/gamehall.com.br/wp-content/uploads/2017/06/bethesda-logo.jpg?ssl=1",
                            Location = "USA",
                            Name = "Bathesda",
                            Url = "studio_bathesda"
                        },
                        new
                        {
                            Id = 6,
                            Email = "contact@ea.com",
                            ImageUrl = "https://wizlogo.com/img/letters/e/ea_logo.jpg",
                            Location = "USA",
                            Name = "Electronic Arts",
                            Url = "studio_ea"
                        },
                        new
                        {
                            Id = 7,
                            Email = "contact@valve.com",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Valve-logo.jpg/1200px-Valve-logo.jpg",
                            Location = "USA",
                            Name = "Valve",
                            Url = "studio_valve"
                        });
                });

            modelBuilder.Entity("Suchimu.Shared.Game", b =>
                {
                    b.HasOne("Suchimu.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Suchimu.Shared.Studio", "Studio")
                        .WithMany()
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Studio");
                });
#pragma warning restore 612, 618
        }
    }
}
